version: "3.7"

services:
  app:
    container_name: app
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: bash -c "npm run dev"
